### ISSUE TITLE
Toggle By KeyBind

### ISSUE THREAD

**Issue by eorroe** [sindresorhus/focus#13]
Can you make this "togglable" instead of having to switch color scheme each time?

**Comment by kevva** [comment]
http://stackoverflow.com/questions/13121687/keyboard-shortcut-to-change-color-scheme-in-sublime-text-2

**Comment by eorroe** [comment]
So I guess I would have to make a plugin to for it to toggle?

**Comment by kevva** [comment]
```
{
    "keys": ["YOUR_SHORTCUT"],
    "command": "set_setting",
    "args":
    {
        "setting": "color_scheme",
        "value": "Packages/Color Scheme - Default/Solarized (Light).tmTheme"
    }
}
```

**Comment by eorroe** [comment]
Ik I did that But if you press it again nothing. I have to either switch tab and then back. Or close and reopen

**Comment by kevva** [comment]
Then install one of the packages linked in the thread. That functionality certainly doesn't belong in this repo.

**Comment by eorroe** [comment]
ok
