### ISSUE TITLE
Is comment content considered as relevant content ?

### ISSUE THREAD

**Issue by Swizz** [sindresorhus/focus#14]
Hi,

You made, comment `.syntax-comment` in the visible color. But, in most case, comment content is not considered as relevant content, isnt it ?

Or is this for doc comment purpose ?

*Tested on Atom*

**Comment by sindresorhus** [comment]
> comment content is not considered as relevant content, isnt it ?

If they're not relevant, why do you have them in your code? Comments should explain the "why" in code. If you don't want it highlighted, it probably means your comments have little value and should be removed.

**Comment by Swizz** [comment]
You may be right. As independent, I am a young boy about clean code principles ^^'
